### ISSUE TITLE
Notice of Modification

### ISSUE THREAD

**Issue by zakwhite** [marklogic/commons-csv#1]
In each file we modify, include a header comment stating that the file has been modified. Suggested language shown below:

Modifications copyright © 2017 MarkLogic Corporation.
September 2017 MarkLogic modified the parser to include the byte count of the original data read.

**Comment by mattsunsjf** [comment]
@zakwhite Please review the change in 93dad54

**Comment by zakwhite** [comment]
Looks good

**Comment by mattsunsjf** [comment]
@jxchen-us Please also review this, so that I will ask for check-in approval from mr. triage to check in a new jar to mlcp.
